"""Old-versus-new results and change report.

python -m strengthened.compare_versions

v1 and v2 share seeds 101-103, both teachers, both regimes, all seven targets and
the eight v1 arms, so those cells are directly comparable. v2 adds seeds 104-110,
two learners and four arms, which v1 never ran; those are reported as new rather
than as changes.
"""
import json
from pathlib import Path

import pandas as pd

from .experiment import ROOT, OUT as V1
from .experiment_v2 import OUT as V2, config

SHARED_SEEDS = [101, 102, 103]
SHARED_MODELS = ['RandomForest', 'LogisticRegression']
HEADLINE = [('shap_sum', 'uniform_sum'), ('shap_sum', 'shuffled_sum'),
            ('select_shap', 'select_random'), ('ps_aug', 'p_aug'), ('p_aug', 'original')]
DEST = ROOT / 'paper/emse/RESULTS_CHANGE_REPORT.md'


def equal_target_mean(scores, arm, control, metric='auc', tuning='independent'):
    keys = ['target', 'seed', 'teacher', 'tuning', 'model']
    s = scores[scores.tuning == tuning]
    m = s[s.arm == arm].merge(s[s.arm == control], on=keys, suffixes=('_a', '_b'),
                              validate='one_to_one')
    if not len(m):
        return None
    m['delta'] = m[metric + '_a'] - m[metric + '_b']
    return float(m.groupby('target').delta.mean().mean())


def report():
    cfg = config()
    v1 = pd.read_csv(V1 / 'scores.csv')
    v2 = pd.read_csv(V2 / 'scores.csv')
    restricted = v2[v2.seed.isin(SHARED_SEEDS) & v2.model.isin(SHARED_MODELS)]

    lines = ['# Old versus new results', '',
             'Generated by `strengthened.compare_versions`. v1 is the three-seed, two-learner, '
             'eight-arm execution in `outputs/revised/strengthening/full`; v2 is the ten-seed, '
             'four-learner, twelve-arm execution in `outputs/revised/strengthening_v2/full`. '
             'Both ran in the same recorded environment. v1 was not modified.', '',
             '## Headline comparisons, ROC-AUC, independent tuning', '',
             'The middle column restricts v2 to the seeds and learners v1 also ran, so it '
             'isolates the effect of the added arms and code path from the effect of the wider '
             'grid. The right column is the full v2 estimate that the manuscript reports.', '',
             '| Comparison | v1 | v2 restricted to v1 grid | v2 full grid |', '|---|---|---|---|']
    for arm, control in HEADLINE:
        a = equal_target_mean(v1, arm, control)
        b = equal_target_mean(restricted, arm, control)
        c = equal_target_mean(v2, arm, control)
        fmt = lambda v: 'not run' if v is None else f'{v:+.4f}'
        lines.append(f'| {arm} vs {control} | {fmt(a)} | {fmt(b)} | {fmt(c)} |')

    new_arms = [a for a in cfg['arms'] if a not in set(v1.arm.unique())]
    lines += ['', '## Comparisons v1 could not make', '',
              'These arms did not exist in v1, so there is no old value to change.', '',
              '| Comparison | v2 full grid | What it establishes |', '|---|---|---|']
    for arm, control, what in [
            ('original', 'prevalence', 'source-only learning against a featureless reference'),
            ('permuted_original', 'original', 'the harness registers total source-signal loss'),
            ('coral', 'original', 'a documented adaptation comparator, transductive'),
            ('ps_aug', 'pn_aug', 'attribution columns against dimension-matched noise'),
            ('pn_aug', 'p_aug', 'the generic added-dimension penalty')]:
        v = equal_target_mean(v2, arm, control)
        lines.append(f'| {arm} vs {control} | {v:+.4f} | {what} |')

    v1m = json.loads((V1 / 'manifest.json').read_text())
    v2m = json.loads((V2 / 'manifest.json').read_text())
    lines += ['', '## Scope', '',
              '| | v1 | v2 |', '|---|---|---|',
              f'| Score records | {v1m["rows"]} | {v2m["rows"]} |',
              f'| Source seeds | 3 | {len(cfg["seeds"])} |',
              f'| Downstream learners | 2 | {len(cfg["models"])} |',
              f'| Arms | 8 | {len(cfg["arms"])} |',
              f'| Checkpoints | 42 | {len(cfg["projects"]) * len(cfg["seeds"]) * len(cfg["teachers"])} |',
              '| Targets | 7 | 7 |', '| Teachers | 2 | 2 |', '| Tuning regimes | 2 | 2 |',
              '', 'New in v2: a featureless reference, a source-label permutation control, a '
              'CORAL adaptation comparator, a dimension-matched augmentation control, seven '
              'further source seeds, two further learners, and leave-one-target-out aggregation '
              'sensitivity for every headline comparison.', '',
              'Unchanged: the seven projects, the 54-metric allowlist, the RealBug label, the '
              'source cap, the teachers, the tuning protocol and the target information boundary.', '',
              'These are descriptive fixed-benchmark effects. Target rotations share training '
              'projects, so they are not independent replications, and no significance, '
              'equivalence or power claim is made from them.']
    DEST.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print('\n'.join(lines[:28]))
    print(f'\nwrote {DEST.relative_to(ROOT)}')


if __name__ == '__main__':
    report()
